
name: First WorkFlow
on: push

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "Hello beta ji"
      - name: Multi line command
        run: |
          node -v
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "Hello Arman how are you now?"
  dependent-job:
    runs-on: macos-latest
    needs: run-shell-command
    steps:
      - name: echo a string for dependent job
        run: echo "Feeling well"          
