name: Test the application
on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    test-and-build:
        runs-on: macos-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Setup Node Environment
            uses: actions/setup-node@v3
            with:
              node-version: 18
              cache: "npm"
          - name: Install Dependency
            run: npm ci
          - name: Check for formatting error
            run: npx lint-staged
          - name: Run ESLint
            run: npm run lint
          - name: Check for Type error
            run: npx tsc
          - name: Show name
            run: echo "Arman Ansari"            
