name: Test the application
on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    test-and-build:
        runs-on: macos-latest
        steps:
          - name: Check for formatting error
            run: npm run check-prettier
          - name: Check for ESLint error
            run: npm run lint
          - name: Check for Type error
            run: npm run typecheck
          - name: Show name
            run: echo "Arman Ansari"            
