name : Working Directory & Shells
on: push

jobs:
  display-wd-info:
    runs-on: macos-latest
    steps:
      - name: Display working directories
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Python Shell
        shell: python
        run: |
          import platform
          print(platform.processor())
          print("Hello World! I am Python language")
          print(2+5)
          print(2*5)